# Site settings
title: Anton Som
email: wyraxlfj@ukr.net
url: https://github.com/jeromelachaud/freelancer-theme
description: "Graphic Designer JavaScript Developer CV and portfolio page"
keywords: "your keywords, separated by commas"
skills: "Graphic Designer | JavaScript Developer"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 9ca9ba #3399cc #18bc9c #80B3FF
  primary-rgb: "51,153,204" #"213,48,99" #"24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Anton "Wyrax" Som © 2021
  
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Wyrax

  - title: linkedin
    url: http://bitbucket.org/jekyll
  - title: facebook
    url: https://github.com/Wyrax

# Postal address (add as many lines as necessary)
address:
  - line: Ukraine, Kyiv
  - line: '02217'

# Credits content
credits: 'This page created with <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer</a>:<br>a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
